load ../teleport.maude

red in TELEPORT : || (a .* 1/2) . |0> (x) |0> (x) |0> + (b .* 1/2) . |0> (x) |0> (x) |1> ||^2 .
red in TELEPORT : || (a .* 1/2) . |1> (x) |0> (x) |0> + (b .* 1/2) . |1> (x) |0> (x) |1> ||^2 .
red in TELEPORT : || (a .* 1/2) . |0> (x) |1> (x) |0> + (b .* 1/2) . |0> (x) |1> (x) |1> ||^2 .
red in TELEPORT : || (a .* 1/2) . |1> (x) |1> (x) |0> + (b .* 1/2) . |1> (x) |1> (x) |1> ||^2 .